In [1]:
#状态 1 2 3
A = [[0.5,0.2,0.3],
     [0.3,0.5,0.2],
     [0.2,0.3,0.5]]

pi = [0.2,0.4,0.4]
# red white
B = [[0.5,0.5],
     [0.4,0.6],
     [0.7,0.3]]

In [2]:
def hmm_viterbi(A,B,pi,O):
    T = len(O)
    N = len(A[0])
    delta = [[0]*N for _ in range(T)]
    psi = [[0]*N for _ in range(T)]
    #step1: init
    for i in range(N):
        delta[0][i] = pi[i]*B[i][O[0]]
        psi[0][i] = 0
    #step2: iter
    for t in range(1,T):
        for i in range(N):
            temp,maxindex = 0,0
            for j in range(N):
                res = delta[t-1][j]*A[j][i]
                if res>temp:
                    temp = res
                    maxindex = j
            delta[t][i] = temp*B[i][O[t]]#delta
            psi[t][i] = maxindex
    #step3: end
    p = max(delta[-1])
    for i in range(N):
        if delta[-1][i] == p:
            i_T = i
    #step4：backtrack
    path = [0]*T
    i_t = i_T
    for t in reversed(range(T-1)):
        i_t = psi[t+1][i_t]
        path[t] = i_t
    path[-1] = i_T
    return delta, psi, path
A = [[0.5,0.2,0.3],[0.3,0.5,0.2],[0.2,0.3,0.5]]
B = [[0.5,0.5],[0.4,0.6],[0.7,0.3]]
pi = [0.2,0.4,0.4]
O = [0,1,0,1]
hmm_viterbi(A,B,pi,O)

([[0.1, 0.16000000000000003, 0.27999999999999997],
  [0.027999999999999997, 0.05039999999999999, 0.041999999999999996],
  [0.007559999999999999, 0.010079999999999999, 0.014699999999999998],
  [0.0018899999999999998, 0.0030239999999999993, 0.0022049999999999995]],
 [[0, 0, 0], [2, 2, 2], [1, 1, 2], [0, 1, 2]],
 [2, 1, 1, 1])

In [3]:
import numpy as np
def viterbi(trainsition_probability, emission_probability, pi, obs_seq):
    #转换为矩阵进行运算
    trainsition_probability = np.array(trainsition_probability)
    emission_probability = np.array(emission_probability)
    pi = np.array(pi)
    obs_seq = [0, 2, 3]
    
    # 最后返回一个Row*Col的矩阵结果
    Row = np.array(trainsition_probability).shape[0]
    Col = len(obs_seq)
    # 定义要返回的矩阵
    F = np.zeros((Row,Col))
    #初始状态
    F[:, 0] = pi*np.transpose(emission_probability[:,obs_seq[0]])
    for t in range(1,Col):
        list_max=[]
        for n in range(Row):
            list_x=list(np.array(F[:,t-1])*np.transpose(trainsition_probability[:,n]))
            #获取最大概率
            list_p=[]
            for i in list_x:
                list_p.append(i*10000)
            list_max.append(max(list_p)/10000)
        F[:,t]=np.array(list_max)*np.transpose(emission_probability[:,obs_seq[t]])
    return F

if __name__=='__main__':
    #隐藏状态
    invisible=['Sunny','Cloud','Rainy']
    #初始状态
    pi=[0.63,0.17,0.20]
    #转移矩阵
    trainsion_probility=[[0.5,0.375,0.125],[0.25,0.125,0.625],[0.25,0.375,0.375]]
    #发射矩阵
    emission_probility=[[0.6,0.2,0.15,0.05],[0.25,0.25,0.25,0.25],[0.05,0.10,0.35,0.5]]
    #最后显示状态
    obs_seq=[0,2,3]
    #最后返回一个Row*Col的矩阵结果
    F=viterbi(trainsion_probility,emission_probility,pi,obs_seq)
    print(F) # Sunny，Cloud，Rainy

[[0.378      0.02835    0.00070875]
 [0.0425     0.0354375  0.00265781]
 [0.01       0.0165375  0.01107422]]
